version: '3.1'

services:
  dev-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: dev
      MYSQL_USER: user
      MYSQL_PASSWORD: mysql
    ports:
      - '3306:3306'
  test-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: mysql
    ports:
      - '3307:3306'
