# fly.toml file generated for orbata-api on 2023-07-13T12:10:45-04:00

app = "orbata-api"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "den"
processes = []

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
